name: Fetch latest data and commit

on:
  repository_dispatch:
  schedule:
    - cron:  '1 11 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl -k "https://efile.fara.gov/bulk/zip/FARA_All_RegistrantDocs.csv.zip" > "FARA_All_RegistrantDocs.csv.zip"
        unzip -q -o "FARA_All_RegistrantDocs.csv.zip"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
